name: paper-env
dependencies:
- openssl=1.0.2d=0
- pip=7.1.2=py27_0
- python=2.7.11=0
- readline=6.2=2
- setuptools=19.1.1=py27_0
- sqlite=3.8.4.1=1
- tk=8.5.18=0
- wheel=0.26.0=py27_1
- zlib=1.2.8=0
- pip:
  - greenlet==0.4.9
  - pandoc-attributes==0.1.7
  - pandoc-eqnos==0.6
  - pandoc-fignos==0.6
  - pandoc-tablenos==0.5
  - pandocfilters==1.2.4

