name: paper-env
dependencies:
- pip=7.1.2=py27_0
- python=2.7.11=0
- setuptools=19.1.1=py27_0
- pip:
  - greenlet==0.4.9
  - pandoc-attributes==0.1.7
  - pandoc-eqnos==0.6
  - pandoc-fignos==0.6
  - pandoc-tablenos==0.5
  - pandocfilters==1.2.4

